// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRu58OsVVP7yR_xL8hA6Wf4mDLRZ5EKh8',
    appId: '1:774679035668:web:20644566f91ed6cbe14c01',
    messagingSenderId: '774679035668',
    projectId: 'muslimsoul-88605',
    authDomain: 'muslimsoul-88605.firebaseapp.com',
    storageBucket: 'muslimsoul-88605.firebasestorage.app',
    measurementId: 'G-VLVLT3H6MN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw3XNkaN7vJZndA7XBw4T_tfEYusi20kM',
    appId: '1:774679035668:android:ab915e3ccc3d337ce14c01',
    messagingSenderId: '774679035668',
    projectId: 'muslimsoul-88605',
    storageBucket: 'muslimsoul-88605.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0tzqaJJXte_1hu9oWS0znGBgJPIcZEQ4',
    appId: '1:774679035668:ios:93d96d62f1918362e14c01',
    messagingSenderId: '774679035668',
    projectId: 'muslimsoul-88605',
    storageBucket: 'muslimsoul-88605.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjects1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0tzqaJJXte_1hu9oWS0znGBgJPIcZEQ4',
    appId: '1:774679035668:ios:93d96d62f1918362e14c01',
    messagingSenderId: '774679035668',
    projectId: 'muslimsoul-88605',
    storageBucket: 'muslimsoul-88605.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjects1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRu58OsVVP7yR_xL8hA6Wf4mDLRZ5EKh8',
    appId: '1:774679035668:web:2111d750cc22b7ade14c01',
    messagingSenderId: '774679035668',
    projectId: 'muslimsoul-88605',
    authDomain: 'muslimsoul-88605.firebaseapp.com',
    storageBucket: 'muslimsoul-88605.firebasestorage.app',
    measurementId: 'G-MX1PFW2HR6',
  );
}
